%YAML 1.1
---
# yaml-language-server: $schema=data-schema.json

metadata:
  animalId: plimbo
  rootPath: test
  minimumSampleTime: 0.05
  sampleOffsetTime: 0.2
  loggingRootPath: D:\hypnose\rawdata\sub-036_id-185\ses-51_date-20250916\behav
  rewardTime: 0.106
  performanceAverageWindow: 5
  initialSequence: Schemas/odourdiscrimination-stage7.yml
  maximumInterOdourPokeTime: 2
    
cameraProperties:
  frameRate: 60
  exposure: 15000
  gain: 10
  roiSourcePoints:
    points:
      - x: 180
        y: 600
      - x: 180
        y: 700
      - x: 1050
        y: 700
      - x: 1050
        y: 600

olfactometerCommands:
  - {name: Default, valvesOpenO0: [], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 400], targetFlowO1: [0, 0, 0, 100, 400]}
  - {name: Zero, valvesOpenO0: [], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 0], targetFlowO1: [0, 0, 0, 0, 0]}
  - {name: Purge, valvesOpenO0: [], valvesOpenO1: [3], endValvesOpenO0: [], endValvesOpenO1: [0], targetFlowO0: [0, 0, 0, 0, 400], targetFlowO1: [0, 0, 0, 100, 400]}
  - {name: OdorA, valvesOpenO0: [0], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [100, 0, 0, 0, 400], targetFlowO1: [0, 0, 0, 0, 400]}
  - {name: OdorB, valvesOpenO0: [], valvesOpenO1: [0], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 400], targetFlowO1: [100, 0, 0, 0, 400]}
  - {name: OdorC, valvesOpenO0: [2], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 100, 0, 400], targetFlowO1: [0, 0, 0, 0, 400]}
  - {name: OdorD, valvesOpenO0: [3], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 100, 400], targetFlowO1: [0, 0, 0, 0, 400]}
  - {name: OdorE, valvesOpenO0: [1], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 100, 0, 0, 400], targetFlowO1: [0, 0, 0, 0, 400]}
  - {name: OdorF, valvesOpenO0: [], valvesOpenO1: [1], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 400], targetFlowO1: [0, 100, 0, 0, 400]}
  - {name: OdorG, valvesOpenO0: [], valvesOpenO1: [2], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 400], targetFlowO1: [0, 0, 100, 0, 400]}