%YAML 1.1
---
# yaml-language-server: $schema=data-schema.json

metadata:
  animalId: plimbo
  rootPath: test
  minimumSampleTime: 0.05
  sampleOffsetTime: 0.1
  loggingRootPath: E:\temp
  rewardTime: 0.045
  performanceAverageWindow: 5
  initialSequence: Schemas/rig1-odourdiscrimination-stage4b-test.yml

cameraProperties:
  frameRate: 30
  exposure: 30000
  gain: 15

olfactometerCommands:
  - {name: Default, valvesOpenO0: [], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 1000], targetFlowO1: [0, 0, 0, 100, 1000]}
  - {name: Purge, valvesOpenO0: [], valvesOpenO1: [3], endValvesOpenO0: [], endValvesOpenO1: [0], targetFlowO0: [0, 0, 0, 0, 1000], targetFlowO1: [0, 0, 0, 100, 1000]}
  - {name: OdorA, valvesOpenO0: [0], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [100, 0, 0, 0, 1000], targetFlowO1: [0, 0, 0, 0, 1000]}
  - {name: OdorB, valvesOpenO0: [], valvesOpenO1: [0], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 1000], targetFlowO1: [100, 0, 0, 0, 1000]}
  - {name: OdorC, valvesOpenO0: [2], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 100, 0, 1000], targetFlowO1: [0, 0, 0, 0, 1000]}
  - {name: OdorD, valvesOpenO0: [3], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 100, 1000], targetFlowO1: [0, 0, 0, 0, 1000]}
  - {name: OdorE, valvesOpenO0: [1], valvesOpenO1: [], endValvesOpenO0: [], endValvesOpenO1: [], targetFlowO0: [0, 100, 0, 0, 1000], targetFlowO1: [0, 0, 0, 0, 1000]}
  - {name: OdorF, valvesOpenO0: [], valvesOpenO1: [1], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 1000], targetFlowO1: [0, 100, 0, 0, 1000]}
  - {name: OdorG, valvesOpenO0: [], valvesOpenO1: [2], endValvesOpenO0: [0], endValvesOpenO1: [], targetFlowO0: [0, 0, 0, 0, 1000], targetFlowO1: [0, 0, 100, 0, 1000]}