//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace DataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RewardCommand
    {
    
        private double _rewardTime;
    
        private int _rewardPosition;
    
        public RewardCommand()
        {
        }
    
        protected RewardCommand(RewardCommand other)
        {
            _rewardTime = other._rewardTime;
            _rewardPosition = other._rewardPosition;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardTime")]
        public double RewardTime
        {
            get
            {
                return _rewardTime;
            }
            set
            {
                _rewardTime = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardPosition")]
        public int RewardPosition
        {
            get
            {
                return _rewardPosition;
            }
            set
            {
                _rewardPosition = value;
            }
        }
    
        public System.IObservable<RewardCommand> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RewardCommand(this)));
        }
    
        public System.IObservable<RewardCommand> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RewardCommand(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("rewardTime = " + _rewardTime + ", ");
            stringBuilder.Append("rewardPosition = " + _rewardPosition);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class OlfactometerStateCommand
    {
    
        private string _name;
    
        private bool _flowEnabledO0;
    
        private bool _flowEnabledO1;
    
        private System.Collections.Generic.List<int> _valvesOpenO0;
    
        private System.Collections.Generic.List<int> _valvesOpenO1;
    
        private System.Collections.Generic.List<int> _endValvesOpenO0;
    
        private System.Collections.Generic.List<int> _endValvesOpenO1;
    
        private System.Collections.Generic.List<double> _targetFlowO0;
    
        private System.Collections.Generic.List<double> _targetFlowO1;
    
        public OlfactometerStateCommand()
        {
            _flowEnabledO0 = true;
            _flowEnabledO1 = true;
            _valvesOpenO0 = new System.Collections.Generic.List<int>();
            _valvesOpenO1 = new System.Collections.Generic.List<int>();
            _endValvesOpenO0 = new System.Collections.Generic.List<int>();
            _endValvesOpenO1 = new System.Collections.Generic.List<int>();
            _targetFlowO0 = new System.Collections.Generic.List<double>();
            _targetFlowO1 = new System.Collections.Generic.List<double>();
        }
    
        protected OlfactometerStateCommand(OlfactometerStateCommand other)
        {
            _name = other._name;
            _flowEnabledO0 = other._flowEnabledO0;
            _flowEnabledO1 = other._flowEnabledO1;
            _valvesOpenO0 = other._valvesOpenO0;
            _valvesOpenO1 = other._valvesOpenO1;
            _endValvesOpenO0 = other._endValvesOpenO0;
            _endValvesOpenO1 = other._endValvesOpenO1;
            _targetFlowO0 = other._targetFlowO0;
            _targetFlowO1 = other._targetFlowO1;
        }
    
        /// <summary>
        /// The alias of this olfactometer command
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="name")]
        [System.ComponentModel.DescriptionAttribute("The alias of this olfactometer command")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable airflow across all channels in olfactometer 0
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="flowEnabledO0")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable airflow across all channels in olfactometer " +
            "0")]
        public bool FlowEnabledO0
        {
            get
            {
                return _flowEnabledO0;
            }
            set
            {
                _flowEnabledO0 = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable airflow across all channels in olfactometer 1
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="flowEnabledO1")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable airflow across all channels in olfactometer " +
            "1")]
        public bool FlowEnabledO1
        {
            get
            {
                return _flowEnabledO1;
            }
            set
            {
                _flowEnabledO1 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="valvesOpenO0")]
        public System.Collections.Generic.List<int> ValvesOpenO0
        {
            get
            {
                return _valvesOpenO0;
            }
            set
            {
                _valvesOpenO0 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="valvesOpenO1")]
        public System.Collections.Generic.List<int> ValvesOpenO1
        {
            get
            {
                return _valvesOpenO1;
            }
            set
            {
                _valvesOpenO1 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="endValvesOpenO0")]
        public System.Collections.Generic.List<int> EndValvesOpenO0
        {
            get
            {
                return _endValvesOpenO0;
            }
            set
            {
                _endValvesOpenO0 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="endValvesOpenO1")]
        public System.Collections.Generic.List<int> EndValvesOpenO1
        {
            get
            {
                return _endValvesOpenO1;
            }
            set
            {
                _endValvesOpenO1 = value;
            }
        }
    
        /// <summary>
        /// The target flow rates of the 5 flow channels on olfactometer 0 in ml/min. Range for the odor channels is 0-100ml/min and 0-1000ml/min for the carrier line.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="targetFlowO0")]
        [System.ComponentModel.DescriptionAttribute("The target flow rates of the 5 flow channels on olfactometer 0 in ml/min. Range f" +
            "or the odor channels is 0-100ml/min and 0-1000ml/min for the carrier line.")]
        public System.Collections.Generic.List<double> TargetFlowO0
        {
            get
            {
                return _targetFlowO0;
            }
            set
            {
                _targetFlowO0 = value;
            }
        }
    
        /// <summary>
        /// The target flow rates of the 5 flow channels on olfactometer 1 in ml/min. Range for the odor channels is 0-100ml/min and 0-1000ml/min for the carrier line.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="targetFlowO1")]
        [System.ComponentModel.DescriptionAttribute("The target flow rates of the 5 flow channels on olfactometer 1 in ml/min. Range f" +
            "or the odor channels is 0-100ml/min and 0-1000ml/min for the carrier line.")]
        public System.Collections.Generic.List<double> TargetFlowO1
        {
            get
            {
                return _targetFlowO1;
            }
            set
            {
                _targetFlowO1 = value;
            }
        }
    
        public System.IObservable<OlfactometerStateCommand> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new OlfactometerStateCommand(this)));
        }
    
        public System.IObservable<OlfactometerStateCommand> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new OlfactometerStateCommand(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("name = " + _name + ", ");
            stringBuilder.Append("flowEnabledO0 = " + _flowEnabledO0 + ", ");
            stringBuilder.Append("flowEnabledO1 = " + _flowEnabledO1 + ", ");
            stringBuilder.Append("valvesOpenO0 = " + _valvesOpenO0 + ", ");
            stringBuilder.Append("valvesOpenO1 = " + _valvesOpenO1 + ", ");
            stringBuilder.Append("endValvesOpenO0 = " + _endValvesOpenO0 + ", ");
            stringBuilder.Append("endValvesOpenO1 = " + _endValvesOpenO1 + ", ");
            stringBuilder.Append("targetFlowO0 = " + _targetFlowO0 + ", ");
            stringBuilder.Append("targetFlowO1 = " + _targetFlowO1);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Valence
    {
    
        private string _command;
    
        private bool _rewarded;
    
        private double _minimumSamplingTime;
    
        private double _maximumSamplingTime;
    
        public Valence()
        {
        }
    
        protected Valence(Valence other)
        {
            _command = other._command;
            _rewarded = other._rewarded;
            _minimumSamplingTime = other._minimumSamplingTime;
            _maximumSamplingTime = other._maximumSamplingTime;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="command")]
        public string Command
        {
            get
            {
                return _command;
            }
            set
            {
                _command = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewarded")]
        public bool Rewarded
        {
            get
            {
                return _rewarded;
            }
            set
            {
                _rewarded = value;
            }
        }
    
        /// <summary>
        /// The minimum sampling time in seconds for a presentation to be considered valid.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="minimumSamplingTime")]
        [System.ComponentModel.DescriptionAttribute("The minimum sampling time in seconds for a presentation to be considered valid.")]
        public double MinimumSamplingTime
        {
            get
            {
                return _minimumSamplingTime;
            }
            set
            {
                _minimumSamplingTime = value;
            }
        }
    
        /// <summary>
        /// The maximum sampling time in seconds for a presentation, completes and is valid after this time.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="maximumSamplingTime")]
        [System.ComponentModel.DescriptionAttribute("The maximum sampling time in seconds for a presentation, completes and is valid a" +
            "fter this time.")]
        public double MaximumSamplingTime
        {
            get
            {
                return _maximumSamplingTime;
            }
            set
            {
                _maximumSamplingTime = value;
            }
        }
    
        public System.IObservable<Valence> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Valence(this)));
        }
    
        public System.IObservable<Valence> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Valence(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("command = " + _command + ", ");
            stringBuilder.Append("rewarded = " + _rewarded + ", ");
            stringBuilder.Append("minimumSamplingTime = " + _minimumSamplingTime + ", ");
            stringBuilder.Append("maximumSamplingTime = " + _maximumSamplingTime);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class RewardCondition
    {
    
        private int _position;
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Valence>> _definition;
    
        public RewardCondition()
        {
            _definition = new System.Collections.Generic.List<System.Collections.Generic.List<Valence>>();
        }
    
        protected RewardCondition(RewardCondition other)
        {
            _position = other._position;
            _definition = other._definition;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="position")]
        public int Position
        {
            get
            {
                return _position;
            }
            set
            {
                _position = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="definition")]
        public System.Collections.Generic.List<System.Collections.Generic.List<Valence>> Definition
        {
            get
            {
                return _definition;
            }
            set
            {
                _definition = value;
            }
        }
    
        public System.IObservable<RewardCondition> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RewardCondition(this)));
        }
    
        public System.IObservable<RewardCondition> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RewardCondition(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("position = " + _position + ", ");
            stringBuilder.Append("definition = " + _definition);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Sequence
    {
    
        private string _name;
    
        private string _defaultCommand;
    
        private string _interCommand;
    
        private double _interCommandTime;
    
        private double _interTrialInterval;
    
        private double _responseTime;
    
        private double _maximumTime;
    
        private System.Collections.Generic.List<RewardCondition> _rewardConditions;
    
        private int _rewardAttempts;
    
        private bool _enableTrialIndicator;
    
        private bool _enableRewardLocationIndicator;
    
        private bool _resetOnReward;
    
        private bool _completionRequiresEngagement;
    
        private bool _skipSampling;
    
        private bool _rewardAvailablePokeReset;
    
        public Sequence()
        {
            _defaultCommand = "Default";
            _interCommand = "Purge";
            _interCommandTime = 0.2D;
            _interTrialInterval = 5D;
            _responseTime = 5D;
            _maximumTime = 10D;
            _rewardConditions = new System.Collections.Generic.List<RewardCondition>();
            _rewardAttempts = 1;
            _enableTrialIndicator = false;
            _enableRewardLocationIndicator = false;
            _resetOnReward = false;
            _completionRequiresEngagement = true;
            _skipSampling = false;
            _rewardAvailablePokeReset = false;
        }
    
        protected Sequence(Sequence other)
        {
            _name = other._name;
            _defaultCommand = other._defaultCommand;
            _interCommand = other._interCommand;
            _interCommandTime = other._interCommandTime;
            _interTrialInterval = other._interTrialInterval;
            _responseTime = other._responseTime;
            _maximumTime = other._maximumTime;
            _rewardConditions = other._rewardConditions;
            _rewardAttempts = other._rewardAttempts;
            _enableTrialIndicator = other._enableTrialIndicator;
            _enableRewardLocationIndicator = other._enableRewardLocationIndicator;
            _resetOnReward = other._resetOnReward;
            _completionRequiresEngagement = other._completionRequiresEngagement;
            _skipSampling = other._skipSampling;
            _rewardAvailablePokeReset = other._rewardAvailablePokeReset;
        }
    
        /// <summary>
        /// The alias of this sequence
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="name")]
        [System.ComponentModel.DescriptionAttribute("The alias of this sequence")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// The default olfactometer command
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="defaultCommand")]
        [System.ComponentModel.DescriptionAttribute("The default olfactometer command")]
        public string DefaultCommand
        {
            get
            {
                return _defaultCommand;
            }
            set
            {
                _defaultCommand = value;
            }
        }
    
        /// <summary>
        /// Command in between presentations
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="interCommand")]
        [System.ComponentModel.DescriptionAttribute("Command in between presentations")]
        public string InterCommand
        {
            get
            {
                return _interCommand;
            }
            set
            {
                _interCommand = value;
            }
        }
    
        /// <summary>
        /// Time for inter-command in seconds
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="interCommandTime")]
        [System.ComponentModel.DescriptionAttribute("Time for inter-command in seconds")]
        public double InterCommandTime
        {
            get
            {
                return _interCommandTime;
            }
            set
            {
                _interCommandTime = value;
            }
        }
    
        /// <summary>
        /// Time between trials in seconds
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="interTrialInterval")]
        [System.ComponentModel.DescriptionAttribute("Time between trials in seconds")]
        public double InterTrialInterval
        {
            get
            {
                return _interTrialInterval;
            }
            set
            {
                _interTrialInterval = value;
            }
        }
    
        /// <summary>
        /// The allowed time window for a subject to make a response following stimulus presentation
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="responseTime")]
        [System.ComponentModel.DescriptionAttribute("The allowed time window for a subject to make a response following stimulus prese" +
            "ntation")]
        public double ResponseTime
        {
            get
            {
                return _responseTime;
            }
            set
            {
                _responseTime = value;
            }
        }
    
        /// <summary>
        /// The maximum time in seconds that a sequence can last
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="maximumTime")]
        [System.ComponentModel.DescriptionAttribute("The maximum time in seconds that a sequence can last")]
        public double MaximumTime
        {
            get
            {
                return _maximumTime;
            }
            set
            {
                _maximumTime = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardConditions")]
        public System.Collections.Generic.List<RewardCondition> RewardConditions
        {
            get
            {
                return _rewardConditions;
            }
            set
            {
                _rewardConditions = value;
            }
        }
    
        /// <summary>
        /// The number of attempts at a reward port allowed before reset.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardAttempts")]
        [System.ComponentModel.DescriptionAttribute("The number of attempts at a reward port allowed before reset.")]
        public int RewardAttempts
        {
            get
            {
                return _rewardAttempts;
            }
            set
            {
                _rewardAttempts = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable indicator for when a trial is ready to be initiated
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="enableTrialIndicator")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable indicator for when a trial is ready to be in" +
            "itiated")]
        public bool EnableTrialIndicator
        {
            get
            {
                return _enableTrialIndicator;
            }
            set
            {
                _enableTrialIndicator = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable indicator for where a reward is available
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="enableRewardLocationIndicator")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable indicator for where a reward is available")]
        public bool EnableRewardLocationIndicator
        {
            get
            {
                return _enableRewardLocationIndicator;
            }
            set
            {
                _enableRewardLocationIndicator = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether a trial should ignore the response time and reset once a reward is given
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="resetOnReward")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether a trial should ignore the response time and reset once" +
            " a reward is given")]
        public bool ResetOnReward
        {
            get
            {
                return _resetOnReward;
            }
            set
            {
                _resetOnReward = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether engagement time must be satisfied before a trial can be considered complete/valid.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="completionRequiresEngagement")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether engagement time must be satisfied before a trial can b" +
            "e considered complete/valid.")]
        public bool CompletionRequiresEngagement
        {
            get
            {
                return _completionRequiresEngagement;
            }
            set
            {
                _completionRequiresEngagement = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether sampling should be skipped (if skipped rewards are available immediately).
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="skipSampling")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether sampling should be skipped (if skipped rewards are ava" +
            "ilable immediately).")]
        public bool SkipSampling
        {
            get
            {
                return _skipSampling;
            }
            set
            {
                _skipSampling = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether when a reward is available if the subject pokes the odour port it resets the trial.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardAvailablePokeReset")]
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether when a reward is available if the subject pokes the od" +
            "our port it resets the trial.")]
        public bool RewardAvailablePokeReset
        {
            get
            {
                return _rewardAvailablePokeReset;
            }
            set
            {
                _rewardAvailablePokeReset = value;
            }
        }
    
        public System.IObservable<Sequence> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Sequence(this)));
        }
    
        public System.IObservable<Sequence> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Sequence(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("name = " + _name + ", ");
            stringBuilder.Append("defaultCommand = " + _defaultCommand + ", ");
            stringBuilder.Append("interCommand = " + _interCommand + ", ");
            stringBuilder.Append("interCommandTime = " + _interCommandTime + ", ");
            stringBuilder.Append("interTrialInterval = " + _interTrialInterval + ", ");
            stringBuilder.Append("responseTime = " + _responseTime + ", ");
            stringBuilder.Append("maximumTime = " + _maximumTime + ", ");
            stringBuilder.Append("rewardConditions = " + _rewardConditions + ", ");
            stringBuilder.Append("rewardAttempts = " + _rewardAttempts + ", ");
            stringBuilder.Append("enableTrialIndicator = " + _enableTrialIndicator + ", ");
            stringBuilder.Append("enableRewardLocationIndicator = " + _enableRewardLocationIndicator + ", ");
            stringBuilder.Append("resetOnReward = " + _resetOnReward + ", ");
            stringBuilder.Append("completionRequiresEngagement = " + _completionRequiresEngagement + ", ");
            stringBuilder.Append("skipSampling = " + _skipSampling + ", ");
            stringBuilder.Append("rewardAvailablePokeReset = " + _rewardAvailablePokeReset);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class HypnoseSession
    {
    
        private Metadata _metadata;
    
        private CameraProperties _cameraProperties;
    
        private System.Collections.Generic.List<OlfactometerStateCommand> _olfactometerCommands;
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Sequence>> _sequences;
    
        public HypnoseSession()
        {
            _olfactometerCommands = new System.Collections.Generic.List<OlfactometerStateCommand>();
            _sequences = new System.Collections.Generic.List<System.Collections.Generic.List<Sequence>>();
        }
    
        protected HypnoseSession(HypnoseSession other)
        {
            _metadata = other._metadata;
            _cameraProperties = other._cameraProperties;
            _olfactometerCommands = other._olfactometerCommands;
            _sequences = other._sequences;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="metadata")]
        public Metadata Metadata
        {
            get
            {
                return _metadata;
            }
            set
            {
                _metadata = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraProperties")]
        public CameraProperties CameraProperties
        {
            get
            {
                return _cameraProperties;
            }
            set
            {
                _cameraProperties = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="olfactometerCommands")]
        public System.Collections.Generic.List<OlfactometerStateCommand> OlfactometerCommands
        {
            get
            {
                return _olfactometerCommands;
            }
            set
            {
                _olfactometerCommands = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="sequences")]
        public System.Collections.Generic.List<System.Collections.Generic.List<Sequence>> Sequences
        {
            get
            {
                return _sequences;
            }
            set
            {
                _sequences = value;
            }
        }
    
        public System.IObservable<HypnoseSession> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HypnoseSession(this)));
        }
    
        public System.IObservable<HypnoseSession> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HypnoseSession(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("metadata = " + _metadata + ", ");
            stringBuilder.Append("cameraProperties = " + _cameraProperties + ", ");
            stringBuilder.Append("olfactometerCommands = " + _olfactometerCommands + ", ");
            stringBuilder.Append("sequences = " + _sequences);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Metadata
    {
    
        private string _animalId;
    
        private string _rootPath;
    
        private double _minimumSampleTime;
    
        private double _sampleOffsetTime;
    
        private double _maximumInterOdourPokeTime = 0.5D;
    
        private double _rewardTime = 0.1D;
    
        private string _loggingRootPath;
    
        public Metadata()
        {
            _animalId = "";
            _rootPath = "";
            _minimumSampleTime = 0.1D;
            _sampleOffsetTime = 0.1D;
            _rewardTime = 0.1D;
            _loggingRootPath = "";
        }
    
        protected Metadata(Metadata other)
        {
            _animalId = other._animalId;
            _rootPath = other._rootPath;
            _minimumSampleTime = other._minimumSampleTime;
            _sampleOffsetTime = other._sampleOffsetTime;
            _maximumInterOdourPokeTime = other._maximumInterOdourPokeTime;
            _rewardTime = other._rewardTime;
            _loggingRootPath = other._loggingRootPath;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="animalId")]
        public string AnimalId
        {
            get
            {
                return _animalId;
            }
            set
            {
                _animalId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rootPath")]
        public string RootPath
        {
            get
            {
                return _rootPath;
            }
            set
            {
                _rootPath = value;
            }
        }
    
        /// <summary>
        /// Minimum amount of time in seconds a subject must sample the port to initiate a trial.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="minimumSampleTime")]
        [System.ComponentModel.DescriptionAttribute("Minimum amount of time in seconds a subject must sample the port to initiate a tr" +
            "ial.")]
        public double MinimumSampleTime
        {
            get
            {
                return _minimumSampleTime;
            }
            set
            {
                _minimumSampleTime = value;
            }
        }
    
        /// <summary>
        /// Time in seconds after sampling offset when subject is considered to have disengaged sampling.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="sampleOffsetTime")]
        [System.ComponentModel.DescriptionAttribute("Time in seconds after sampling offset when subject is considered to have disengag" +
            "ed sampling.")]
        public double SampleOffsetTime
        {
            get
            {
                return _sampleOffsetTime;
            }
            set
            {
                _sampleOffsetTime = value;
            }
        }
    
        /// <summary>
        /// Maximum time after interCommandTime that subject has to repoke - otherwise trial ends.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="maximumInterOdourPokeTime")]
        [System.ComponentModel.DescriptionAttribute("Maximum time after interCommandTime that subject has to repoke - otherwise trial " +
            "ends.")]
        public double MaximumInterOdourPokeTime
        {
            get
            {
                return _maximumInterOdourPokeTime;
            }
            set
            {
                _maximumInterOdourPokeTime = value;
            }
        }
    
        /// <summary>
        /// Time in seconds to deliver rewards
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rewardTime")]
        [System.ComponentModel.DescriptionAttribute("Time in seconds to deliver rewards")]
        public double RewardTime
        {
            get
            {
                return _rewardTime;
            }
            set
            {
                _rewardTime = value;
            }
        }
    
        /// <summary>
        /// The local root folder to save data for this session
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="loggingRootPath")]
        [System.ComponentModel.DescriptionAttribute("The local root folder to save data for this session")]
        public string LoggingRootPath
        {
            get
            {
                return _loggingRootPath;
            }
            set
            {
                _loggingRootPath = value;
            }
        }
    
        public System.IObservable<Metadata> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Metadata(this)));
        }
    
        public System.IObservable<Metadata> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Metadata(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("animalId = " + _animalId + ", ");
            stringBuilder.Append("rootPath = " + _rootPath + ", ");
            stringBuilder.Append("minimumSampleTime = " + _minimumSampleTime + ", ");
            stringBuilder.Append("sampleOffsetTime = " + _sampleOffsetTime + ", ");
            stringBuilder.Append("maximumInterOdourPokeTime = " + _maximumInterOdourPokeTime + ", ");
            stringBuilder.Append("rewardTime = " + _rewardTime + ", ");
            stringBuilder.Append("loggingRootPath = " + _loggingRootPath);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class CameraProperties
    {
    
        private double _frameRate;
    
        private double _exposure;
    
        private double _gain;
    
        public CameraProperties()
        {
            _frameRate = 60D;
            _exposure = 19000D;
            _gain = 0D;
        }
    
        protected CameraProperties(CameraProperties other)
        {
            _frameRate = other._frameRate;
            _exposure = other._exposure;
            _gain = other._gain;
        }
    
        /// <summary>
        /// The target camera frame rate in frames per second.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frameRate")]
        [System.ComponentModel.DescriptionAttribute("The target camera frame rate in frames per second.")]
        public double FrameRate
        {
            get
            {
                return _frameRate;
            }
            set
            {
                _frameRate = value;
            }
        }
    
        /// <summary>
        /// The frame exposure in microseconds.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="exposure")]
        [System.ComponentModel.DescriptionAttribute("The frame exposure in microseconds.")]
        public double Exposure
        {
            get
            {
                return _exposure;
            }
            set
            {
                _exposure = value;
            }
        }
    
        /// <summary>
        /// the gain of the camera sensor.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="gain")]
        [System.ComponentModel.DescriptionAttribute("the gain of the camera sensor.")]
        public double Gain
        {
            get
            {
                return _gain;
            }
            set
            {
                _gain = value;
            }
        }
    
        public System.IObservable<CameraProperties> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraProperties(this)));
        }
    
        public System.IObservable<CameraProperties> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraProperties(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("frameRate = " + _frameRate + ", ");
            stringBuilder.Append("exposure = " + _exposure + ", ");
            stringBuilder.Append("gain = " + _gain);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<RewardCommand> source)
        {
            return Process<RewardCommand>(source);
        }

        public System.IObservable<string> Process(System.IObservable<OlfactometerStateCommand> source)
        {
            return Process<OlfactometerStateCommand>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Valence> source)
        {
            return Process<Valence>(source);
        }

        public System.IObservable<string> Process(System.IObservable<RewardCondition> source)
        {
            return Process<RewardCondition>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Sequence> source)
        {
            return Process<Sequence>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HypnoseSession> source)
        {
            return Process<HypnoseSession>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Metadata> source)
        {
            return Process<Metadata>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraProperties> source)
        {
            return Process<CameraProperties>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RewardCommand>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<OlfactometerStateCommand>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Valence>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<RewardCondition>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Sequence>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HypnoseSession>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Metadata>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraProperties>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<HypnoseSession>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}