//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace SequenceSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Sequence
    {
    
        private string _name;
    
        private string _defaultCommand;
    
        private string _interCommand;
    
        private double _interCommandTime;
    
        private double _interTrialInterval;
    
        private double _responseTime;
    
        private System.Collections.Generic.List<RewardCondition> _rewardConditions;
    
        private int _rewardAttempts;
    
        private bool _enableTrialEndIndicator;
    
        private string _enableRewardLocationIndicator;
    
        private bool _resetOnReward;
    
        private bool _completionRequiresEngagement;
    
        private bool _skipSampling;
    
        private bool _rewardAvailablePokeReset;
    
        private bool _enableTrialStartIndicator;
    
        private int _sequenceLengthIndex;
    
        private double _sampleOffsetTime;
    
        private double _rewardVolume;
    
        public Sequence()
        {
            _defaultCommand = "Default";
            _interCommand = "Purge";
            _interCommandTime = 0.2D;
            _interTrialInterval = 0D;
            _responseTime = 5D;
            _rewardConditions = new System.Collections.Generic.List<RewardCondition>();
            _rewardAttempts = 1;
            _enableTrialEndIndicator = false;
            _enableRewardLocationIndicator = "None";
            _resetOnReward = false;
            _completionRequiresEngagement = true;
            _skipSampling = false;
            _rewardAvailablePokeReset = false;
            _enableTrialStartIndicator = false;
            _sequenceLengthIndex = 0;
            _sampleOffsetTime = 0.1D;
            _rewardVolume = 1D;
        }
    
        protected Sequence(Sequence other)
        {
            _name = other._name;
            _defaultCommand = other._defaultCommand;
            _interCommand = other._interCommand;
            _interCommandTime = other._interCommandTime;
            _interTrialInterval = other._interTrialInterval;
            _responseTime = other._responseTime;
            _rewardConditions = other._rewardConditions;
            _rewardAttempts = other._rewardAttempts;
            _enableTrialEndIndicator = other._enableTrialEndIndicator;
            _enableRewardLocationIndicator = other._enableRewardLocationIndicator;
            _resetOnReward = other._resetOnReward;
            _completionRequiresEngagement = other._completionRequiresEngagement;
            _skipSampling = other._skipSampling;
            _rewardAvailablePokeReset = other._rewardAvailablePokeReset;
            _enableTrialStartIndicator = other._enableTrialStartIndicator;
            _sequenceLengthIndex = other._sequenceLengthIndex;
            _sampleOffsetTime = other._sampleOffsetTime;
            _rewardVolume = other._rewardVolume;
        }
    
        /// <summary>
        /// The alias of this sequence
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The alias of this sequence")]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        /// <summary>
        /// The default olfactometer command
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The default olfactometer command")]
        public string DefaultCommand
        {
            get
            {
                return _defaultCommand;
            }
            set
            {
                _defaultCommand = value;
            }
        }
    
        /// <summary>
        /// Command in between presentations
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Command in between presentations")]
        public string InterCommand
        {
            get
            {
                return _interCommand;
            }
            set
            {
                _interCommand = value;
            }
        }
    
        /// <summary>
        /// Time for inter-command in seconds
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Time for inter-command in seconds")]
        public double InterCommandTime
        {
            get
            {
                return _interCommandTime;
            }
            set
            {
                _interCommandTime = value;
            }
        }
    
        /// <summary>
        /// Time between trials
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Time between trials")]
        public double InterTrialInterval
        {
            get
            {
                return _interTrialInterval;
            }
            set
            {
                _interTrialInterval = value;
            }
        }
    
        /// <summary>
        /// The allowed time window for a subject to make a response following stimulus presentation
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The allowed time window for a subject to make a response following stimulus prese" +
            "ntation")]
        public double ResponseTime
        {
            get
            {
                return _responseTime;
            }
            set
            {
                _responseTime = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<RewardCondition> RewardConditions
        {
            get
            {
                return _rewardConditions;
            }
            set
            {
                _rewardConditions = value;
            }
        }
    
        /// <summary>
        /// The number of attempts at a reward port allowed before reset.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The number of attempts at a reward port allowed before reset.")]
        public int RewardAttempts
        {
            get
            {
                return _rewardAttempts;
            }
            set
            {
                _rewardAttempts = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable indicator until the trial is completed and reward is available
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable indicator until the trial is completed and r" +
            "eward is available")]
        public bool EnableTrialEndIndicator
        {
            get
            {
                return _enableTrialEndIndicator;
            }
            set
            {
                _enableTrialEndIndicator = value;
            }
        }
    
        /// <summary>
        /// String specifying whether to enable indicator for where a reward is available and for which ports to be enabled
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("String specifying whether to enable indicator for where a reward is available and" +
            " for which ports to be enabled")]
        public string EnableRewardLocationIndicator
        {
            get
            {
                return _enableRewardLocationIndicator;
            }
            set
            {
                _enableRewardLocationIndicator = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether a trial should ignore the response time and reset once a reward is given
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether a trial should ignore the response time and reset once" +
            " a reward is given")]
        public bool ResetOnReward
        {
            get
            {
                return _resetOnReward;
            }
            set
            {
                _resetOnReward = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether engagement time must be satisfied before a trial can be considered complete/valid.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether engagement time must be satisfied before a trial can b" +
            "e considered complete/valid.")]
        public bool CompletionRequiresEngagement
        {
            get
            {
                return _completionRequiresEngagement;
            }
            set
            {
                _completionRequiresEngagement = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether sampling should be skipped (if skipped rewards are available immediately).
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether sampling should be skipped (if skipped rewards are ava" +
            "ilable immediately).")]
        public bool SkipSampling
        {
            get
            {
                return _skipSampling;
            }
            set
            {
                _skipSampling = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether when a reward is available if the subject pokes the odour port it resets the trial.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether when a reward is available if the subject pokes the od" +
            "our port it resets the trial.")]
        public bool RewardAvailablePokeReset
        {
            get
            {
                return _rewardAvailablePokeReset;
            }
            set
            {
                _rewardAvailablePokeReset = value;
            }
        }
    
        /// <summary>
        /// Boolean specifying whether to enable indicator for when a trial is ready to be started
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Boolean specifying whether to enable indicator for when a trial is ready to be st" +
            "arted")]
        public bool EnableTrialStartIndicator
        {
            get
            {
                return _enableTrialStartIndicator;
            }
            set
            {
                _enableTrialStartIndicator = value;
            }
        }
    
        /// <summary>
        /// The number of odours in the sequence in index form
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The number of odours in the sequence in index form")]
        public int SequenceLengthIndex
        {
            get
            {
                return _sequenceLengthIndex;
            }
            set
            {
                _sequenceLengthIndex = value;
            }
        }
    
        /// <summary>
        /// Time in seconds after sampling offset when subject is considered to have disengaged sampling.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Time in seconds after sampling offset when subject is considered to have disengag" +
            "ed sampling.")]
        public double SampleOffsetTime
        {
            get
            {
                return _sampleOffsetTime;
            }
            set
            {
                _sampleOffsetTime = value;
            }
        }
    
        /// <summary>
        /// Volume of reward in uL
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Volume of reward in uL")]
        public double RewardVolume
        {
            get
            {
                return _rewardVolume;
            }
            set
            {
                _rewardVolume = value;
            }
        }
    
        public System.IObservable<Sequence> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Sequence(this)));
        }
    
        public System.IObservable<Sequence> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Sequence(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Name = " + _name + ", ");
            stringBuilder.Append("DefaultCommand = " + _defaultCommand + ", ");
            stringBuilder.Append("InterCommand = " + _interCommand + ", ");
            stringBuilder.Append("InterCommandTime = " + _interCommandTime + ", ");
            stringBuilder.Append("InterTrialInterval = " + _interTrialInterval + ", ");
            stringBuilder.Append("ResponseTime = " + _responseTime + ", ");
            stringBuilder.Append("RewardConditions = " + _rewardConditions + ", ");
            stringBuilder.Append("RewardAttempts = " + _rewardAttempts + ", ");
            stringBuilder.Append("EnableTrialEndIndicator = " + _enableTrialEndIndicator + ", ");
            stringBuilder.Append("EnableRewardLocationIndicator = " + _enableRewardLocationIndicator + ", ");
            stringBuilder.Append("ResetOnReward = " + _resetOnReward + ", ");
            stringBuilder.Append("CompletionRequiresEngagement = " + _completionRequiresEngagement + ", ");
            stringBuilder.Append("SkipSampling = " + _skipSampling + ", ");
            stringBuilder.Append("RewardAvailablePokeReset = " + _rewardAvailablePokeReset + ", ");
            stringBuilder.Append("EnableTrialStartIndicator = " + _enableTrialStartIndicator + ", ");
            stringBuilder.Append("SequenceLengthIndex = " + _sequenceLengthIndex + ", ");
            stringBuilder.Append("SampleOffsetTime = " + _sampleOffsetTime + ", ");
            stringBuilder.Append("RewardVolume = " + _rewardVolume);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class RewardCondition
    {
    
        private int _position;
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Valence>> _definition;
    
        public RewardCondition()
        {
            _definition = new System.Collections.Generic.List<System.Collections.Generic.List<Valence>>();
        }
    
        protected RewardCondition(RewardCondition other)
        {
            _position = other._position;
            _definition = other._definition;
        }
    
        public int Position
        {
            get
            {
                return _position;
            }
            set
            {
                _position = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<Valence>> Definition
        {
            get
            {
                return _definition;
            }
            set
            {
                _definition = value;
            }
        }
    
        public System.IObservable<RewardCondition> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new RewardCondition(this)));
        }
    
        public System.IObservable<RewardCondition> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new RewardCondition(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Position = " + _position + ", ");
            stringBuilder.Append("Definition = " + _definition);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Valence
    {
    
        private string _command;
    
        private bool _rewarded;
    
        private double _minimumSamplingTime;
    
        private double _maximumSamplingTime;
    
        private int _index;
    
        public Valence()
        {
        }
    
        protected Valence(Valence other)
        {
            _command = other._command;
            _rewarded = other._rewarded;
            _minimumSamplingTime = other._minimumSamplingTime;
            _maximumSamplingTime = other._maximumSamplingTime;
            _index = other._index;
        }
    
        public string Command
        {
            get
            {
                return _command;
            }
            set
            {
                _command = value;
            }
        }
    
        public bool Rewarded
        {
            get
            {
                return _rewarded;
            }
            set
            {
                _rewarded = value;
            }
        }
    
        /// <summary>
        /// The minimum sampling time in seconds for a presentation to be considered valid.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The minimum sampling time in seconds for a presentation to be considered valid.")]
        public double MinimumSamplingTime
        {
            get
            {
                return _minimumSamplingTime;
            }
            set
            {
                _minimumSamplingTime = value;
            }
        }
    
        /// <summary>
        /// The maximum sampling time in seconds for a presentation, completes and is valid after this time.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The maximum sampling time in seconds for a presentation, completes and is valid a" +
            "fter this time.")]
        public double MaximumSamplingTime
        {
            get
            {
                return _maximumSamplingTime;
            }
            set
            {
                _maximumSamplingTime = value;
            }
        }
    
        /// <summary>
        /// The index of the command in the sequence, used for multi-command sequences.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("The index of the command in the sequence, used for multi-command sequences.")]
        public int Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }
    
        public System.IObservable<Valence> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Valence(this)));
        }
    
        public System.IObservable<Valence> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Valence(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Command = " + _command + ", ");
            stringBuilder.Append("Rewarded = " + _rewarded + ", ");
            stringBuilder.Append("MinimumSamplingTime = " + _minimumSamplingTime + ", ");
            stringBuilder.Append("MaximumSamplingTime = " + _maximumSamplingTime + ", ");
            stringBuilder.Append("Index = " + _index);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HypnoseSequence
    {
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Sequence>> _sequences;
    
        private string _nextSequence;
    
        private double _performaceCriterion;
    
        public HypnoseSequence()
        {
            _sequences = new System.Collections.Generic.List<System.Collections.Generic.List<Sequence>>();
            _performaceCriterion = 0.8D;
        }
    
        protected HypnoseSequence(HypnoseSequence other)
        {
            _sequences = other._sequences;
            _nextSequence = other._nextSequence;
            _performaceCriterion = other._performaceCriterion;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<Sequence>> Sequences
        {
            get
            {
                return _sequences;
            }
            set
            {
                _sequences = value;
            }
        }
    
        /// <summary>
        /// Path to .yml file of the next sequence to advance to.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Path to .yml file of the next sequence to advance to.")]
        public string NextSequence
        {
            get
            {
                return _nextSequence;
            }
            set
            {
                _nextSequence = value;
            }
        }
    
        /// <summary>
        /// Performance that must be reached before advancing to the next sequence.
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Performance that must be reached before advancing to the next sequence.")]
        public double PerformaceCriterion
        {
            get
            {
                return _performaceCriterion;
            }
            set
            {
                _performaceCriterion = value;
            }
        }
    
        public System.IObservable<HypnoseSequence> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HypnoseSequence(this)));
        }
    
        public System.IObservable<HypnoseSequence> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HypnoseSequence(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Sequences = " + _sequences + ", ");
            stringBuilder.Append("NextSequence = " + _nextSequence + ", ");
            stringBuilder.Append("PerformaceCriterion = " + _performaceCriterion);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }
}